// Central data store for seed data and mock data
export const SAMPLE_JOBS = [
  {
    id: "job1",
    title: "React Frontend Intern",
    description: "Join our growing startup as a React developer intern. You will build UI components, work with REST APIs, and collaborate with a small but passionate team. Great learning opportunity with real project experience.",
    category: "Technical & IT",
    payType: "monthly" as const,
    payAmount: 8000,
    duration: "3 months",
    location: "Remote",
    isRemote: true,
    skillsRequired: ["React", "JavaScript", "HTML/CSS"],
    status: "active" as const,
    applicantsCount: 14,
    hiredCount: 1,
    spotsAvailable: 2,
    startDate: "Immediate",
    employer: {
      companyName: "TechStart Labs",
      city: "Bangalore",
      rating: 4.5,
      isVerifiedBusiness: true,
    },
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job2",
    title: "Home Tutor — Grade 10 Maths",
    description: "We are looking for a patient and knowledgeable tutor for a Grade 10 student preparing for board exams. Sessions will be 1.5 hours, 4 days a week at the student's home in Anna Nagar.",
    category: "Academic & Tutoring",
    payType: "hourly" as const,
    payAmount: 500,
    duration: "6 months",
    location: "Chennai",
    isRemote: false,
    skillsRequired: ["Maths", "Physics"],
    status: "active" as const,
    applicantsCount: 7,
    hiredCount: 0,
    spotsAvailable: 1,
    startDate: "Next Monday",
    employer: {
      companyName: "Mrs. Lakshmi Narayan (Parent)",
      city: "Chennai",
      rating: 5.0,
      isVerifiedBusiness: false,
    },
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job3",
    title: "Event Photography Assistant",
    description: "Assist our lead photographer at corporate events, weddings, and brand launches. You will handle lighting, manage props, edit photos in Lightroom, and deliver within 48 hours. Own DSLR is a plus.",
    category: "Events & Gigs",
    payType: "fixed" as const,
    payAmount: 2000,
    duration: "Per event",
    location: "Bangalore",
    isRemote: false,
    skillsRequired: ["Photography", "Photoshop"],
    status: "active" as const,
    applicantsCount: 11,
    hiredCount: 2,
    spotsAvailable: 3,
    startDate: "Weekends",
    employer: {
      companyName: "PixelFrame Studios",
      city: "Bangalore",
      rating: 4.7,
      isVerifiedBusiness: true,
    },
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job4",
    title: "Data Entry Operator",
    description: "Enter and validate product catalog data into our e-commerce platform. Work involves Excel sheets, basic data cleaning, and uploading product images. Flexible hours, work from home.",
    category: "Data & Research",
    payType: "monthly" as const,
    payAmount: 3500,
    duration: "1 month (extendable)",
    location: "Remote",
    isRemote: true,
    skillsRequired: ["Excel", "Data Entry", "MS Office"],
    status: "active" as const,
    applicantsCount: 22,
    hiredCount: 3,
    spotsAvailable: 5,
    startDate: "Immediate",
    employer: {
      companyName: "ShopEasy India",
      city: "Mumbai",
      rating: 4.2,
      isVerifiedBusiness: true,
    },
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job5",
    title: "Social Media Manager",
    description: "Create and schedule content for Instagram, LinkedIn, and Twitter for our EdTech brand. Responsibilities include post design (Canva), caption writing, hashtag research, and monthly analytics reports.",
    category: "Digital Marketing",
    payType: "monthly" as const,
    payAmount: 6000,
    duration: "Ongoing",
    location: "Remote",
    isRemote: true,
    skillsRequired: ["Social Media", "Canva", "Content Writing"],
    status: "active" as const,
    applicantsCount: 19,
    hiredCount: 1,
    spotsAvailable: 1,
    startDate: "Immediate",
    employer: {
      companyName: "EduBridge Academy",
      city: "Pune",
      rating: 4.6,
      isVerifiedBusiness: true,
    },
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job6",
    title: "Logo Designer (Brand Identity)",
    description: "Design a professional logo and basic brand kit (colors, fonts, business card) for a new fitness studio. Deliverables: 3 logo concepts, final files in AI + PNG formats, and a brand guideline doc.",
    category: "Creative & Design",
    payType: "fixed" as const,
    payAmount: 1500,
    duration: "5–7 days",
    location: "Remote",
    isRemote: true,
    skillsRequired: ["Logo Design", "Illustrator", "Figma"],
    status: "active" as const,
    applicantsCount: 8,
    hiredCount: 0,
    spotsAvailable: 1,
    startDate: "Immediate",
    employer: {
      companyName: "FitCore Studio",
      city: "Hyderabad",
      rating: 4.8,
      isVerifiedBusiness: false,
    },
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job7",
    title: "Content Writer — Tech Blog",
    description: "Write SEO-optimized tech articles (1000–1500 words) on topics like AI, cybersecurity, and Web3. Experience with WordPress and basic keyword research preferred. Flexible deadlines.",
    category: "Content & Writing",
    payType: "per-word" as const,
    payAmount: 2,
    duration: "Ongoing",
    location: "Remote",
    isRemote: true,
    skillsRequired: ["Content Writing", "SEO", "WordPress"],
    status: "active" as const,
    applicantsCount: 16,
    hiredCount: 4,
    spotsAvailable: 3,
    startDate: "Immediate",
    employer: {
      companyName: "ByteMedia Publishing",
      city: "Delhi",
      rating: 4.4,
      isVerifiedBusiness: true,
    },
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job8",
    title: "WiFi & Router Setup Technician",
    description: "Visit homes and offices to set up WiFi routers, configure network settings, troubleshoot connectivity issues, and set up printers. Serve areas: Madhapur, Hitech City, Gachibowli.",
    category: "Technical & IT",
    payType: "fixed" as const,
    payAmount: 800,
    duration: "Per visit",
    location: "Hyderabad",
    isRemote: false,
    skillsRequired: ["WiFi Setup", "Hardware", "Laptop Repair"],
    status: "active" as const,
    applicantsCount: 5,
    hiredCount: 2,
    spotsAvailable: 3,
    startDate: "Immediate",
    employer: {
      companyName: "HomeConnect Services",
      city: "Hyderabad",
      rating: 4.9,
      isVerifiedBusiness: true,
    },
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job9",
    title: "Video Editor — Instagram Reels",
    description: "Edit 15–30 second Reels for a lifestyle brand. Responsibilities: trim footage, add music, transitions, captions, color grading. Deliver 10–15 reels per month. Adobe Premiere or CapCut ok.",
    category: "Creative & Design",
    payType: "monthly" as const,
    payAmount: 4000,
    duration: "Ongoing",
    location: "Remote",
    isRemote: true,
    skillsRequired: ["Video Editing", "Premiere Pro"],
    status: "active" as const,
    applicantsCount: 13,
    hiredCount: 1,
    spotsAvailable: 2,
    startDate: "Immediate",
    employer: {
      companyName: "GlowUp Lifestyle",
      city: "Mumbai",
      rating: 4.3,
      isVerifiedBusiness: false,
    },
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job10",
    title: "Shop Assistant (Evening Shift)",
    description: "Assist customers in a busy clothing retail store in Linking Road. Duties: stock management, billing, customer guidance, and end-of-day cash counting. 5 PM – 9 PM, 5 days a week.",
    category: "Local & On-site",
    payType: "per-day" as const,
    payAmount: 350,
    duration: "Ongoing",
    location: "Mumbai",
    isRemote: false,
    skillsRequired: ["Customer Service"],
    status: "active" as const,
    applicantsCount: 9,
    hiredCount: 1,
    spotsAvailable: 2,
    startDate: "Next Week",
    employer: {
      companyName: "StyleZone Retail",
      city: "Mumbai",
      rating: 4.1,
      isVerifiedBusiness: true,
    },
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job11",
    title: "Online English Tutor (Spoken + Written)",
    description: "Conduct 1-hour online sessions (Google Meet / Zoom) for students and working professionals looking to improve spoken and written English. Sessions can be scheduled at your convenience.",
    category: "Academic & Tutoring",
    payType: "hourly" as const,
    payAmount: 400,
    duration: "Ongoing",
    location: "Remote",
    isRemote: true,
    skillsRequired: ["English", "Content Writing"],
    status: "active" as const,
    applicantsCount: 12,
    hiredCount: 3,
    spotsAvailable: 5,
    startDate: "Immediate",
    employer: {
      companyName: "FluentEdge Learning",
      city: "Chennai",
      rating: 4.7,
      isVerifiedBusiness: true,
    },
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job12",
    title: "PPT Design Specialist",
    description: "Design beautiful, professional PowerPoint/Google Slides presentations for businesses, investors, and academic projects. Typical projects are 15–25 slides. Quick turnaround (24–48 hours).",
    category: "Creative & Design",
    payType: "fixed" as const,
    payAmount: 1200,
    duration: "Per project",
    location: "Remote",
    isRemote: true,
    skillsRequired: ["PowerPoint", "Canva", "Figma"],
    status: "active" as const,
    applicantsCount: 17,
    hiredCount: 5,
    spotsAvailable: 3,
    startDate: "Immediate",
    employer: {
      companyName: "SlideWorks Agency",
      city: "Bangalore",
      rating: 4.6,
      isVerifiedBusiness: true,
    },
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job13",
    title: "AI Data Labeling — Image & Text",
    description: "Label images, transcribe audio clips, and annotate text data for AI training datasets. Work from home, flexible hours, task-based pay. No prior experience needed — training provided.",
    category: "Quick Tasks",
    payType: "fixed" as const,
    payAmount: 500,
    duration: "Ongoing, flexible",
    location: "Remote",
    isRemote: true,
    skillsRequired: ["Data Labeling", "Data Entry"],
    status: "active" as const,
    applicantsCount: 34,
    hiredCount: 12,
    spotsAvailable: 20,
    startDate: "Immediate",
    employer: {
      companyName: "DataAnnotate AI",
      city: "Bangalore",
      rating: 4.0,
      isVerifiedBusiness: true,
    },
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job14",
    title: "Local Tourist Guide — Mahabalipuram",
    description: "Guide domestic and international tourists at the UNESCO World Heritage Site. You should know the history of the monuments and be able to explain in English and Tamil. Weekends only.",
    category: "Travel & Guide",
    payType: "fixed" as const,
    payAmount: 1000,
    duration: "Per day (weekends)",
    location: "Chennai",
    isRemote: false,
    skillsRequired: ["Local Guide", "English", "Tamil"],
    status: "active" as const,
    applicantsCount: 4,
    hiredCount: 0,
    spotsAvailable: 2,
    startDate: "Next Weekend",
    employer: {
      companyName: "Heritage Tours India",
      city: "Chennai",
      rating: 4.9,
      isVerifiedBusiness: true,
    },
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "job15",
    title: "Resume & LinkedIn Profile Writer",
    description: "Create professional, ATS-friendly resumes and LinkedIn profiles for fresh graduates and professionals. Deliverables: resume in Word + PDF, cover letter template, and optimized LinkedIn summary.",
    category: "Content & Writing",
    payType: "fixed" as const,
    payAmount: 800,
    duration: "2–3 days per client",
    location: "Remote",
    isRemote: true,
    skillsRequired: ["Content Writing", "MS Office", "Proofreading"],
    status: "active" as const,
    applicantsCount: 21,
    hiredCount: 7,
    spotsAvailable: 5,
    startDate: "Immediate",
    employer: {
      companyName: "CareerCraft Services",
      city: "Hyderabad",
      rating: 4.5,
      isVerifiedBusiness: false,
    },
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const SAMPLE_STUDENTS = [
  {
    id: "s1",
    name: "Arjun Kumar",
    college: "IIT Madras",
    branch: "Computer Science",
    year: "3rd Year",
    city: "Chennai",
    skills: ["React", "JavaScript", "Python", "Node.js"],
    rating: 4.8,
    completedJobs: 9,
    totalEarnings: 21500,
    profileImage: "",
    bio: "CSE student at IIT Madras passionate about web development and open source.",
  },
  {
    id: "s2",
    name: "Priya Sharma",
    college: "BITS Pilani",
    branch: "Electronics & Communication",
    year: "2nd Year",
    city: "Bangalore",
    skills: ["Photoshop", "Canva", "Video Editing", "Content Writing"],
    rating: 4.9,
    completedJobs: 14,
    totalEarnings: 34200,
    profileImage: "",
    bio: "Creative designer with a passion for visual storytelling and brand identity.",
  },
  {
    id: "s3",
    name: "Rahul Reddy",
    college: "NIT Trichy",
    branch: "Mechanical Engineering",
    year: "4th Year",
    city: "Hyderabad",
    skills: ["Maths", "Physics", "Excel", "Data Entry"],
    rating: 4.6,
    completedJobs: 6,
    totalEarnings: 12000,
    profileImage: "",
    bio: "Engineering student offering tutoring and technical services.",
  },
  {
    id: "s4",
    name: "Anjali Menon",
    college: "Anna University",
    branch: "Information Technology",
    year: "3rd Year",
    city: "Chennai",
    skills: ["Content Writing", "SEO", "Social Media", "WordPress"],
    rating: 4.7,
    completedJobs: 11,
    totalEarnings: 18700,
    profileImage: "",
    bio: "Digital marketing enthusiast and content creator with 2+ years of freelancing experience.",
  },
  {
    id: "s5",
    name: "Karthik Subramaniam",
    college: "VIT Vellore",
    branch: "Computer Science",
    year: "1st Year",
    city: "Coimbatore",
    skills: ["Python", "Data Labeling", "Translation", "Tamil"],
    rating: 4.5,
    completedJobs: 3,
    totalEarnings: 4500,
    profileImage: "",
    bio: "Enthusiastic first-year student eager to gain real-world experience.",
  },
];

export const TESTIMONIALS = [
  {
    name: "Priya Sharma",
    role: "BITS Pilani, 2nd Year ECE",
    content: "StudentConnect helped me earn ₹34,000 in 3 months doing video editing and design work — all while keeping up with my coursework. The platform is incredibly easy to use.",
    rating: 5,
    type: "student",
    earned: "₹34,200",
    jobs: 14,
  },
  {
    name: "Suresh Kumar",
    role: "Founder, CreativeEdge Studio",
    content: "We've hired 8 students through StudentConnect and the quality has been outstanding. Fast applications, verified profiles, and students who genuinely care about delivering great work.",
    rating: 5,
    type: "employer",
    hired: 8,
    savings: "60% cost savings",
  },
  {
    name: "Arjun Kumar",
    role: "IIT Madras, 3rd Year CSE",
    content: "Got my first React internship through this platform at ₹8,000/mo. The skill matching is spot-on — every job recommendation was relevant to my profile. Highly recommend!",
    rating: 5,
    type: "student",
    earned: "₹21,500",
    jobs: 9,
  },
  {
    name: "Kavitha Rajan",
    role: "Director, EduBridge Academy",
    content: "StudentConnect is a game-changer for small businesses. We found a talented social media manager in 2 days. Responsive, skilled, and professional. Will definitely use again.",
    rating: 5,
    type: "employer",
    hired: 4,
    savings: "Saved 15 hours of recruitment",
  },
];

export const JOB_CATEGORY_ICONS: Record<string, string> = {
  "Academic & Tutoring": "📚",
  "Technical & IT": "💻",
  "Creative & Design": "🎨",
  "Content & Writing": "✍️",
  "Events & Gigs": "🎪",
  "Local & On-site": "🏪",
  "Digital Marketing": "📱",
  "Data & Research": "📊",
  "Quick Tasks": "⚡",
  "Travel & Guide": "🗺️",
};

export const PLATFORM_STATS = {
  students: "2,418",
  jobs: "892",
  earned: "₹18.4L",
  employers: "346",
};
